### ISSUE TITLE
Integração não aparece disponível para adicionar

### ISSUE THREAD

**Issue by jonferreira** [dgomes/ha_erse#15]
Boas.

Copiei a pasta erse para a /custom_components e reiniciei.

Tenho a tipica mensagem "2021-09-04 15:07:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration erse which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant" pelo que sei que a integração foi carregada.

Mas depois em Integrations - Add Integrations quando procuro por ela não aparece nada.

**Comment by dgomes** [comment]
Como vez pela mensagem tem q estar la :)

Usa a feature de pesquisa e escrever "erse"

**Comment by jonferreira** [comment]
![image](https://user-images.githubusercontent.com/7714292/132105883-503b4ad3-cba6-43bd-9432-dd5251ea7c2e.png)

**Comment by dgomes** [comment]
qq coisa muito esquisita ai... não poderás ter uma versão antiga do erse ?

Ha experimentaste instalar via HACS ?

**Comment by jonferreira** [comment]
versão antiga do erse não de certeza pq só o descobri hoje, depois de actualizar para a última versão do HA

HACS não tenho instalado, sempre fiz manualmente sem problemas.

**Comment by dgomes** [comment]
como fizeste o download ?

**Comment by jonferreira** [comment]
fiz download aqui do github

![image](https://user-images.githubusercontent.com/7714292/132106210-c15f1858-3adb-4141-8f58-48a965f2343c.png)

**Comment by dgomes** [comment]
não ha mais erros no log do HA ?

(podes actualizar entretanto saiu uma versão nova)

**Comment by jonferreira** [comment]
o que foi atualizado? o HA?

com relação a erros não, o que tenho é de outro componente que está a dar erro porque o roomba está desligado

**Comment by jonferreira** [comment]
epah vais te rir - cache! limpei a cache do chrome e ja aparece!!

agora e não querendo abusar, eu tenho tarifa simples sem bihorario pelo que tenho o meu utility_meter assim:

```
utility_meter:
  daily_energy:
    source: sensor.home_power_meter
    cycle: daily
    #tariffs:
    #  - peak
    #  - offpeak
  monthly_energy:
    source: sensor.home_power_meter
    cycle: monthly
    #tariffs:
    #  - peak
    #  - offpeak
```

ou seja, sem tariffs. não me aparece nenhum sensor para escolher durante o setup pelo que parece-me que tenho de activar pelo menos a tariff peak? se assim assumo tambem que devo escolher o daily_energy?

obrigado
