### ISSUE TITLE
[home] is an invalid option for [erse].

### ISSUE THREAD

**Issue by bernardovalente** [dgomes/ha_erse#2]
Hey could you help me set this up, i don't know what i'm doing wrong:

```
erse:
  home:
    operator: EDP
    plan: Simples
    utility_meters:
    - utility_meter.totalizador
```

Thanks for your work
