### ISSUE TITLE
mais info

### ISSUE THREAD

**Issue by hmmatos** [dgomes/ha_erse#3]
Ola, existe mais informação de como usar este componente em algum lado? 

não consigo passar deste erro: 

` Invalid config for [sensor.erse]: [utility_meters] is an invalid option for [sensor.erse]. Check: sensor.erse->utility_meters. (See ?, line ?). `

configuration.yaml

```
utility_meter:
    energia_diario_consumed:
        source: sensor.energy_consumed
        cycle: daily
        tariffs:
            -  Fora de Vazio
            -  Vazio
    energia_mensal_consumed:
        source: sensor.energy_consumed
        cycle: monthly
        tariffs:
            - Fora de Vazio
            - Vazio
            
sensor:
     - platform: erse
       operator: EDP
       plan: Tri-horário - ciclo diário
       utility_meters:
           - utility_meter.totalizador
```

estou a usar os sensores da Efergy

**Comment by dgomes** [comment]
A erse não é um sensor, é uma integração própria. Assim não deve ficar debaixo de "sensor:"

Aconselho que se junte a http://cpha.pt onde tens vários exemplos de configuração

**Comment by hmmatos** [comment]
"sensor:" é que esta no exemplo de configuração que esta na pagina do Git.
No forum da cpha não encontro nada recente tudo usa um componente electricity que esta (DEPRECATED)
https://github.com/dgomes/home-assistant-custom-components/tree/master/electricity

Também fiz registo no forum para poder postar e pedir ajuda quando faço o login no forum fica assim: ttps://forum.cpha.pt/w/get-user-data e a pagina fica em branco... 

Vou ver se arranjo ajuda em outro lado, obrigado.

**Comment by dgomes** [comment]
OK... ja vi que tenho de actualizar o exemplo YAML

Mas podes instalar através da interface gráfica! É só procurar nas integrações

Em relação ao CPHA vou reportar

**Comment by dgomes** [comment]
Podes formatar melhor o teu código para perceber o erro no YAML ?

**Comment by hmmatos** [comment]
Desculpa, não reparei que tinha ficado tudo desformatado. 
Depois de teres dito para tirar do "sensor" meti assim e ja não dá erro, ainda não funciona mas ja não dá erro.

```
utility_meter:                                                                                                                                                                                              
   energia_diario_consumed:                                                                                                                                                                                 
     source: sensor.energy_consumed                                                                                                                                                                         
     cycle: daily                                                                                                                                                                                           
     tariffs:                                                                                                                                                                                               
       - Fora de Vazio                                                                                                                                                                                      
       - Vazio                                                                                                                                                                                              
   energia_mensal_consumed:                                                                                                                                                                                 
     source: sensor.energy_consumed                                                                                                                                                                         
     cycle: monthly                                                                                                                                                                                         
     tariffs:                                                                                                                                                                                               
       - Fora de Vazio                                                                                                                                                                                      
       - Vazio                                                                                                                                                                                              
                                                                                                                                                                                                            
erse:                                                                                                                                                                                                       
   operator: EDP                                                                                                                                                                                            
   plan: Tri-horário - ciclo diário                                                                                                                                                                       
   utility_meters:                                                                                                                                                                                          
   - utility_meter.totalizador
```
Meti o a pasta do projeto em `config/custom_components/erse`

`__init__.py`     
`__pycache__`     
`config_flow.py`  
`const.py`        
`manifest.json`   
`sensor.py`       
`strings.json`    
`translations`

**Comment by dgomes** [comment]
coloca mais 2 espaços:
```
   - utility_meter.totalizador
```

Actualizei o README onde lhe faltavam os espaços

**Comment by hmmatos** [comment]
Ola Diogo, 

ja não tenho erro nenhum, mas não consigo por a trocar a tarifa corretamente com o Tri-horário - ciclo diário. 

![Captura de ecrã 2020-09-24, às 17 55 14](https://user-images.githubusercontent.com/4135196/94175817-1ee00e00-fe8f-11ea-861b-24f28bc5cecd.png)

```
######################## configuration.yaml ############################

erse:
   operator: EDP
   plan: Tri-horário - ciclo diário
   utility_meters:
     - utility_meter.totalizador

utility_meter:
  energia_diaria_consumida:
    source: sensor.efergy_832996
    cycle: daily
    tariffs:
      - Ponta
      - Cheias
      - Vazio
  energia_mensal_consumida: 
  source: sensor.efergy_832996
    cycle: daily
    tariffs:
      - Ponta
      - Cheias
      - Vazio


######################## automations.yaml ############################

- alias: tariff change
  trigger:
    platform: state
    entity_id: electricity.utility_edp
  action:
    - service: utility_meter.select_tariff
      entity_id: utility_meter.energia_diaria_consumida
      data_template:
        tariff: "{{ trigger.to_state.state }}"
    - service: utility_meter.select_tariff
      entity_id: utility_meter.energia_mensal_consumida
      data_template:
        tariff: "{{ trigger.to_state.state }}"
```

Na automation em todos os exemplos que vi no furom da cpha eles usam o electricity como entity id no trigger, mas eu não tenho este modulo, como é que fica agora com o erse?

Falta-me alguma coisa? 

PS: desculpa, ainda não consigo postar no furom da cpha

**Comment by dgomes** [comment]
Com o erse não precisas de criar nenhum automação...

O electricity (componente antigo) é que precisava.

**Comment by hmmatos** [comment]
OK, então assim esta bem? 

configuration.yaml
```
erse:
   operator: EDP
   plan: Tri-horário - ciclo diário
   utility_meters:
     - utility_meter.totalizador

utility_meter:
  energia_diaria_consumida:
    source: sensor.efergy_832996
    cycle: daily
    tariffs:
      - Ponta
      - Cheias
      - Vazio
  energia_mensal_consumida: 
  source: sensor.efergy_832996
    cycle: daily
    tariffs:
      - Ponta
      - Cheias
      - Vazio
```
Porque assim não esta a mudar a tarifa.

![Captura de ecrã 2020-09-24, às 21 15 23](https://user-images.githubusercontent.com/4135196/94195867-7b512680-feab-11ea-8f4d-d52ffae2838e.png)

Segundo o site da EDP - https://www.edp.pt/particulares/apoio-cliente/opcao-horaria.aspx

Devia mudar para cheias as 21h

**Comment by dgomes** [comment]
Onde tens:
```
     - utility_meter.totalizador
```

deves ter:
```
  - utility_meter.energia_diaria_consumida
  - utility_meter.energia_mensal_consumida
```

**Comment by dgomes** [comment]
no energia_mensal_consumida deve mudar o cycle para mensal tb... ;)

**Comment by hmmatos** [comment]
Fica igual, ele nunca muda de Ponta

![Captura de ecrã 2020-09-25, às 00 03 51](https://user-images.githubusercontent.com/4135196/94208913-db9f9280-fec2-11ea-90b6-32849112aab6.png)

A esta hora (00:05) devia estar em Vazio

![Captura de ecrã 2020-09-25, às 00 07 56](https://user-images.githubusercontent.com/4135196/94209038-376a1b80-fec3-11ea-910a-8469092d72be.png)

```
utility_meter:
  energia_diaria_consumida:
    source: sensor.efergy_832996
    cycle: daily
    tariffs:
      - Ponta
      - Cheias
      - Vazio
  energia_mensal_consumida: 
    source: sensor.efergy_832996
    cycle: monthly
    tariffs:
      - Ponta
      - Cheias
      - Vazio

erse:                                                     
   operator: EDP                
   plan: Tri-horário - ciclo diário                           
   utility_meters:                                              
     - utility_meter.energia_diaria_consumida
     - utility_meter.energia_mensal_consumida
```
Tens alguma ideia para fazer debug a isto? 
Há alguma maneira de testar o erse?
