### ISSUE TITLE
Poder usar um widget com o tempo que falta para a próxima mudança de tarifa 

### ISSUE THREAD

**Issue by pixolex** [dgomes/ha_erse#37]
Era interessante haver um atributo ou sensor com o tempo que falta para mudar de tarifa (cheia, ponta ou vazio). Assim era possível ter um widget no Android com um contador decrescente para a próxima mudança de tarifa.

**Comment by denkyem** [comment]
> Era interessante haver um atributo ou sensor com o tempo que falta para mudar de tarifa (cheia, ponta ou vazio). Assim era possível ter um widget no Android com um contador decrescente para a próxima mudança de tarifa.

Enquanto aguardamos que seja adicionado na integração, podes usar a API que criei para isto.
Parece estar sem erros a calcular os periodos Vazio e Fora de Vazio, mas não dou garantias 😅


Tens de adicionar o sensor Date&Time ISO
[Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=time_date)

E depois criar 2 sensores REST no yaml

```
sensor:
  - platform: rest
    name: Eletricidade - BiHorario Semanal - Next Tariff
    unique_id: eletricidade_bihorario_semanal_next_tariff
    resource_template: https://carlosmpereira.outsystemscloud.com/Electricity_API/rest/ElectricTariff/GetNextTariff_v3?isDaylightSavingTime={{ now().timetuple().tm_isdst > 0 }}&BihorarioId=1&Datetime={{ states('sensor.date_time_iso') }}
    value_template: "{{ value_json.StartTime }}"
    json_attributes:
      - NextTariff
    device_class: timestamp

  - platform: rest
    name: Eletricidade - BiHorario Diario - Next Tariff
    unique_id: eletricidade_bihorario_diario_next_tariff
    resource_template: https://carlosmpereira.outsystemscloud.com/Electricity_API/rest/ElectricTariff/GetNextTariff_v3?BihorarioId=2&Datetime={{ states('sensor.date_time_iso') }}
    value_template: "{{ value_json.StartTime }}"
    json_attributes:
      - NextTariff
    device_class: timestamp
```
