### ISSUE TITLE
Custo acesso rede reset

### ISSUE THREAD

**Issue by Joao-Sousa-71** [dgomes/ha_erse#39]
Isto provavelmente não é um _issue_ mas sim uma questão sobre o cálculo de custo acesso à rede e eventualmente meu desconhecimento.
Tenho defenido os seguintes Utility Meters:

```
  netmeter_daily_total_energy_consumed:
    source: sensor.energy_import_netmeter
    cycle: daily
    offset:
      minutes: 2
    tariffs:
      - Fora de Vazio
      - Vazio
    delta_values: true      
  netmeter_monthly_total_energy_consumed:  
    source: sensor.energy_import_netmeter
    cycle: monthly
    offset:
      days: 20
    tariffs:
      - Fora de Vazio
      - Vazio      
    delta_values: true
```
 E estes são os custos:

![image](https://github.com/user-attachments/assets/eab8ca52-74cc-4be4-bd6a-f30b45889a98)

Acontece que ao dia 20 (offset mensal quando é reinicializado o custo de acesso as redes, no dia 21 às 00:00 começa logo com €3.11 (1.1058 * 3) mas não deveria ser 1.1058 *2 (dia 20 e 21)!

![image](https://github.com/user-attachments/assets/a16afc7a-b179-49fc-8d65-6e986fc3b5a8)

Será que era por ter antes  _dois utility meters_  aqui na nesta configuração e só deveria ter o mensal?

![image](https://github.com/user-attachments/assets/b6a0ec9f-eac0-44ac-986f-81675b2e31bc)

 
É que fiz hoje essa alteração mas agora tenho que esperar até ao dia 21 do proximo mês para se possivel precisava de esclarecimento.
Muito Obrigado.
