### ISSUE TITLE
EDP e GALP only

### ISSUE THREAD

**Issue by etpedro** [dgomes/ha_erse#6]
Viva Duarte,

Quando adiciono a integração ERSE via Integrations Page no HA apenas tenho a opção de selecionar a GALP e a EDP, não me aparecem a Iberdrola e a GoldEnergy.
![image](https://user-images.githubusercontent.com/25817178/103234343-5d2a1500-4937-11eb-922c-7ea28f6ac823.png)

**Comment by dgomes** [comment]
actualiza via HACS, ja estamos na versão v1.0.2

**Comment by etpedro** [comment]
Olá Diogo,

Estou na v1.0.2 e a dificuldade mantém-se:
![image](https://user-images.githubusercontent.com/25817178/103272711-770a3d00-49b5-11eb-80f0-3c76be5e2ddd.png)

![image](https://user-images.githubusercontent.com/25817178/103273548-770b3c80-49b7-11eb-9bfa-9b494f4c6eee.png)

**Comment by etpedro** [comment]
O problema deverá estar na minha instância de HA. Removi o ha_erse do HACS e voltei a instalar e agora nas Integrações não me aparece disponivel para escolher.

Já passaste por algo deste género que possas dar uma luz?

**Comment by dgomes** [comment]
<img width="420" alt="Screenshot 2020-12-29 at 09 52 23" src="https://user-images.githubusercontent.com/137684/103275201-90ae8300-49bb-11eb-90d7-ab42a70b5d13.png">

verifica que só tens mesmo a versão do HACS

**Comment by etpedro** [comment]
Viva Diogo,

Foi uma questão de timing e já apareceu, contudo, independentemente do operador que escolha aparecem sempre todos os planos para escolha:
![image](https://user-images.githubusercontent.com/25817178/103291342-683a7f00-49e3-11eb-80ed-0df2bc32e429.png)

E independentemente do plano que escolha, a 3ª box aparece sempre a vazio e sem a possibilidade de fazer o submit:
![image](https://user-images.githubusercontent.com/25817178/103291648-26f69f00-49e4-11eb-8901-ee651deb48aa.png)

**Comment by dgomes** [comment]
Aparecem efectivamente todos os planos... não tenho ainda maneira de resolver esse filtro :( talvez com próximas versões do HA

A terceira caixa está vazia porque não criaste ainda nenhum `utility_meter` (tem q ser via YAML)

**Comment by etpedro** [comment]
Ah ok, pensei que fosse algum problema meu. Sendo limitação do HA, é deixar estar até ser possível resolver. Infelizmente não tenho conhecimentos para conseguir ajudar.

Quanto ao utility_meter, tenho alguns criados. Isto estava a funcionar com a integração **electricity** mas mudei de operador e queria colocar a nova.

```
#Configuração Consumo Energia
utility_meter:
  daily_energy_termoacumulador:
    source: sensor.socket_termoacumulador_energy_today
    cycle: daily
  monthly_energy_termoacumulador:
    source: sensor.socket_termoacumulador_energy_today
    cycle: monthly
  daily_energy_ender3:
    source: sensor.sonoffpow01_energy_today
    cycle: daily
  monthly_energy_ender3:
    source: sensor.sonoffpow01_energy_today
    cycle: monthly

```
