### ISSUE TITLE
How to use with wibeee?

### ISSUE THREAD

**Issue by abacao** [dgomes/ha_erse#7]
Hello and congratulations for your work.

I'm using Wibeee and the entity providing power is a sensor.

When installing the component, I can select the provider and tarif (in my case Galp Simples) but I can't select nothing on the third drop-down box.

I imagine the component should be available with this:

```
electricity:
  utility_galp:
    country: Portugal
    operator: Galp
    plan: Simples

utility_meter:
  energia_mensal:
    source: sensor.wibeee_phase4_active_energy
    cycle: montly
    tariffs: Simples
```

Is this correct?

Why can't I select nothing on the third drop-down box?
